# Generated by Django 5.1.2 on 2024-10-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_latest_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latest_products',
            options={'verbose_name_plural': 'Latest Products'},
        ),
    ]
