# Generated by Django 5.1.2 on 2024-10-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
